### ISSUE TITLE
Building Master has wrong references for commons-libraries

### ISSUE THREAD

**Issue by jjdestef3** [bhits/consent2share#21]
Hi,

I'd like to build all the components of v3.5. I've run the build on the common-libraries which produces the 1.17.0-SNAPSHOT jars and installs them in my local m2 repo. I set up a development environment as described in the developers guide (the current guide is for v3.4 so not sure if there's an updated one for v3.5). I cloned the master branch on all the repos. The pom file references in many of the projects don't match the common jars version (1.17.0-SNAPSHOT) produced from the common-libraries project. I could go through and change the poms, but, is the code in master v3.5? Also, has anyone built the master branches against the current commons-libraries project?

Thanks

**Comment by burcakulug** [comment]
Hi @jjdestef3,

Actually, if you check the [3.5.0 release notes](https://github.com/bhits/consent2share/releases/tag/3.5.0), it refers to individual version for each repository in the release. When you checkout those tags for each repository, you should have everything for `3.5.0` release. 

For common-libraries, you can checkout the required version tags from the [common-libraries releases](https://github.com/bhits/common-libraries/releases) and build/install them to your local repository.

Please let us know if this resolved your issue.

**Comment by jjdestef3** [comment]
Hi @burcakulug,

Sorry for not getting back sooner and also for not looking at the release notes in more detail. Your response did resolve my issue.


Thanks

**Comment by burcakulug** [comment]
You're welcome @jjdestef3 , please do not hesitate to ask if you have any more questions.
Thanks.
